[package]
name = "regsort"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
walkdir = "2.5.0"
regex = "1.11.1"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
serial_test = "3.2.0"
notify = "8.0.0"
